# project1

In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("student.csv")
df=pd.DataFrame(data)
df

     Name  Age Gender  Python  Maths  DBMS  English  Attendance
0    Aman   20      M    85.0     78  90.0       72          92
1    Riya   19      F    92.0     88  95.0       90          96
2   Rahul   21      M    65.0     72  68.0       70          75
3   Sneha   20      F    78.0     85  80.0       82          88
4   Karan   19      M    45.0     58  52.0       60          65
5   Priya   20      F    88.0     91  86.0       89          94
6   Arjun   21      M    72.0     68  75.0       71          80
7    Neha   19      F    95.0     94   NaN       96          98
8   Vikas   20      M     NaN     62  58.0       64          70
9  Anjali   21      F    81.0     79  84.0       86          90

In [4]:
df.columns

Index(['Name', 'Age', 'Gender', 'Python', 'Maths', 'DBMS', 'English',
       'Attendance'],
      dtype='str')

In [5]:
df.dtypes

Name              str
Age             int64
Gender            str
Python        float64
Maths           int64
DBMS          float64
English         int64
Attendance      int64
dtype: object

In [6]:
df["total_marks"]=df[["Python","Maths","DBMS","English"]].sum(axis=1)
df

     Name  Age Gender  Python  Maths  DBMS  English  Attendance  total_marks
0    Aman   20      M    85.0     78  90.0       72          92        325.0
1    Riya   19      F    92.0     88  95.0       90          96        365.0
2   Rahul   21      M    65.0     72  68.0       70          75        275.0
3   Sneha   20      F    78.0     85  80.0       82          88        325.0
4   Karan   19      M    45.0     58  52.0       60          65        215.0
5   Priya   20      F    88.0     91  86.0       89          94        354.0
6   Arjun   21      M    72.0     68  75.0       71          80        286.0
7    Neha   19      F    95.0     94   NaN       96          98        285.0
8   Vikas   20      M     NaN     62  58.0       64          70        184.0
9  Anjali   21      F    81.0     79  84.0       86          90        330.0

In [7]:
df["percentage"]=(df["total_marks"])/4
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50
7,Neha,19,F,95.0,94,NaN,96,98,285.0,71.25
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50

In [8]:
def grade(percentage):
    if percentage>=90:
        return  ("A+")
    elif percentage>=80:
        return  ("A")
    elif percentage>=70:
        return ("B")
    elif percentage>=60:
        return ("C")
    elif percentage>=50:
        return ("D")
    elif percentage<50:
        return ("F")

In [9]:
df["grade"]=df["percentage"].apply(grade)
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B
7,Neha,19,F,95.0,94,NaN,96,98,285.0,71.25,B
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A

In [10]:
df["Rank"]=df["percentage"].rank(ascending=False).astype(int)
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6
7,Neha,19,F,95.0,94,NaN,96,98,285.0,71.25,B,7
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F,10
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3

In [11]:
def status(percentage):
    if percentage>=90:
        return  ("Excellent")
    elif percentage>=80:
        return  ("Very good")
    elif percentage>=70:
        return ("Good")
    elif percentage>=60:
        return ("Pass")
    elif percentage>=50:
        return ("Pass")
    elif percentage<50:
        return ("Fail")

df["Status"]=df["percentage"].apply(status)
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank,Status
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4,Very good
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1,Excellent
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8,Pass
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4,Very good
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9,Pass
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2,Very good
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6,Good
7,Neha,19,F,95.0,94,NaN,96,98,285.0,71.25,B,7,Good
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F,10,Fail
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3,Very good

In [12]:
# df.isna().sum()
df.isna().sum().sum()

np.int64(2)

In [13]:
df.fillna(0,inplace=True)

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank,Status
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4,Very good
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1,Excellent
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8,Pass
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4,Very good
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9,Pass
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2,Very good
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6,Good
7,Neha,19,F,95.0,94,0.0,96,98,285.0,71.25,B,7,Good
8,Vikas,20,M,0.0,62,58.0,64,70,184.0,46.00,F,10,Fail
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3,Very good

In [14]:
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank,Status
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4,Very good
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1,Excellent
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8,Pass
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4,Very good
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9,Pass
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2,Very good
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6,Good
7,Neha,19,F,95.0,94,0.0,96,98,285.0,71.25,B,7,Good
8,Vikas,20,M,0.0,62,58.0,64,70,184.0,46.00,F,10,Fail
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3,Very good

In [15]:
name=df[df["Name"]=="Riya"]
print("=====================search student====================")
print(name.T.to_string(header=False))

=====================search student====================
Name              Riya
Age                 19
Gender               F
Python            92.0
Maths               88
DBMS              95.0
English             90
Attendance          96
total_marks      365.0
percentage       91.25
grade               A+
Rank                 1
Status       Excellent

In [16]:
# name =input("enter the name:")

# def Student_report(name):
#     s=df[df["Name"].str.lower()==name.lower()]
#     if s.empty:
#         print("Student not found")
#     else:
#         return (s.T.to_string(header=False))

# df["Name"].apply(Student_report)

In [17]:
name =input("enter the name:")

s=df[df["Name"].str.lower()==name.lower()]
if s.empty:
    print("Student not found")
else:
    print("======== STUDENT DETAIL =========")
    print()
    print (s.T.to_string(header=False))

======== STUDENT DETAIL =========

Name              Riya
Age                 19
Gender               F
Python            92.0
Maths               88
DBMS              95.0
English             90
Attendance          96
total_marks      365.0
percentage       91.25
grade               A+
Rank                 1
Status       Excellent

In [18]:
topper=df[df["percentage"]==df["percentage"].max()]
print(topper.T.to_string(header=False))

Name              Riya
Age                 19
Gender               F
Python            92.0
Maths               88
DBMS              95.0
English             90
Attendance          96
total_marks      365.0
percentage       91.25
grade               A+
Rank                 1
Status       Excellent

In [19]:
average_marks=df["total_marks"].mean()
print("average_marks :",average_marks)

average_marks : 294.4

In [20]:
pass_student=df[df["percentage"]>=50][["Name","total_marks","grade","Status"]].to_string(index=False)
print(pass_student)

  Name  total_marks grade    Status
  Aman        325.0     A Very good
  Riya        365.0    A+ Excellent
 Rahul        275.0     C      Pass
 Sneha        325.0     A Very good
 Karan        215.0     D      Pass
 Priya        354.0     A Very good
 Arjun        286.0     B      Good
  Neha        285.0     B      Good
Anjali        330.0     A Very good

In [21]:
#6
failed_student=df[df["percentage"]<50][["Name","total_marks","grade","Status"]]
print(failed_student.to_string(index=False))

 Name  total_marks grade Status
Vikas        184.0     F   Fail

In [22]:
# 7
short_attendance=df[df["Attendance"]<75]
print(short_attendance.to_string(index=False))

 Name  Age Gender  Python  Maths  DBMS  English  Attendance  total_marks  percentage grade  Rank Status
Karan   19      M    45.0     58  52.0       60          65        215.0       53.75     D     9   Pass
Vikas   20      M     0.0     62  58.0       64          70        184.0       46.00     F    10   Fail

In [23]:
# 8
print("=============== Class Statistics =============\n")
total_students=len(df)
print("total_students :",total_students)

=============== Class Statistics =============

total_students : 10

In [24]:
# df["Gender"].value_counts()
male_students=df[df["Gender"]=="M"]["Name"].count()
print("male_students :",male_students)
female_students=df[df["Gender"]=="F"]["Name"].count()
print("female_students :",female_students)

male_students : 5
female_students : 5

In [25]:
Highest_percentage=df["percentage"].max()
print("Highest_percentage :",Highest_percentage)
lowest_percentage=df["percentage"].min()
print("lowest_percentage :",lowest_percentage)

Highest_percentage : 91.25
lowest_percentage : 46.0

In [26]:
average_percentage=df["percentage"].mean()
print("Average_percentage :",average_percentage)
average_attendance=df["Attendance"].mean()
print("Average_Attendance :",average_attendance)

Average_percentage : 73.6
Average_Attendance : 84.8

In [27]:
passed_students=df[df["percentage"]>=50]["Name"].count()
print("Passed Students :",passed_students)
fail_students=df[df["percentage"]<50]["Name"].count()
print("Failed Students :",fail_students)

Passed Students : 9
Failed Students : 1

In [ ]:
Attendance_shortage=df[df["Attendance"]<75]["Name"].count()
print("Attendance_shortage :",Attendance_shortage)

Attendance_shortage : 2

In [38]:
topper=df[df["percentage"]==df["percentage"].max()]["Name"]
print("Topper :",topper.to_string(index=False))

Topper : Riya