## project 1

In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("student.csv")
df=pd.DataFrame(data)
df

     Name  Age Gender  Python  Maths  DBMS  English  Attendance
0    Aman   20      M    85.0     78  90.0       72          92
1    Riya   19      F    92.0     88  95.0       90          96
2   Rahul   21      M    65.0     72  68.0       70          75
3   Sneha   20      F    78.0     85  80.0       82          88
4   Karan   19      M    45.0     58  52.0       60          65
5   Priya   20      F    88.0     91  86.0       89          94
6   Arjun   21      M    72.0     68  75.0       71          80
7    Neha   19      F    95.0     94   NaN       96          98
8   Vikas   20      M     NaN     62  58.0       64          70
9  Anjali   21      F    81.0     79  84.0       86          90

In [4]:
df.head()

    Name  Age Gender  Python  Maths  DBMS  English  Attendance
0   Aman   20      M    85.0     78  90.0       72          92
1   Riya   19      F    92.0     88  95.0       90          96
2  Rahul   21      M    65.0     72  68.0       70          75
3  Sneha   20      F    78.0     85  80.0       82          88
4  Karan   19      M    45.0     58  52.0       60          65

In [5]:
df.tail()

     Name  Age Gender  Python  Maths  DBMS  English  Attendance
5   Priya   20      F    88.0     91  86.0       89          94
6   Arjun   21      M    72.0     68  75.0       71          80
7    Neha   19      F    95.0     94   NaN       96          98
8   Vikas   20      M     NaN     62  58.0       64          70
9  Anjali   21      F    81.0     79  84.0       86          90

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     str
 1   Age         10 non-null     int64
 2   Gender      10 non-null     str
 3   Python      9 non-null      float64
 4   Maths       10 non-null     int64
 5   DBMS        9 non-null      float64
 6   English     10 non-null     int64
 7   Attendance  10 non-null     int64
dtypes: float64(2), int64(4), str(2)
memory usage: 772.0 bytes

In [7]:
df.shape

(10, 8)

In [8]:
df.columns

Index(['Name', 'Age', 'Gender', 'Python', 'Maths', 'DBMS', 'English',
       'Attendance'],
      dtype='str')

In [9]:
df.dtypes

Name              str
Age             int64
Gender            str
Python        float64
Maths           int64
DBMS          float64
English         int64
Attendance      int64
dtype: object

In [10]:
df[["Python","Maths","DBMS","English"]].mean()

Python     77.888889
Maths      77.500000
DBMS       76.444444
English    78.000000
dtype: float64

In [11]:
df["total_marks"]=df[["Python","Maths","DBMS","English"]].sum(axis=1)
df

     Name  Age Gender  Python  Maths  DBMS  English  Attendance  total_marks
0    Aman   20      M    85.0     78  90.0       72          92        325.0
1    Riya   19      F    92.0     88  95.0       90          96        365.0
2   Rahul   21      M    65.0     72  68.0       70          75        275.0
3   Sneha   20      F    78.0     85  80.0       82          88        325.0
4   Karan   19      M    45.0     58  52.0       60          65        215.0
5   Priya   20      F    88.0     91  86.0       89          94        354.0
6   Arjun   21      M    72.0     68  75.0       71          80        286.0
7    Neha   19      F    95.0     94   NaN       96          98        285.0
8   Vikas   20      M     NaN     62  58.0       64          70        184.0
9  Anjali   21      F    81.0     79  84.0       86          90        330.0

In [12]:
df["percentage"]=(df["total_marks"])/4
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50
7,Neha,19,F,95.0,94,NaN,96,98,285.0,71.25
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50

In [34]:
def grade(percentage):
    if percentage>=90:
        return  ("A+")
    elif percentage>=80:
        return  ("A")
    elif percentage>=70:
        return ("B")
    elif percentage>=60:
        return ("C")
    elif percentage>=50:
        return ("D")
    elif percentage<50:
        return ("F")

In [35]:
df["grade"]=df["percentage"].apply(grade)
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6
7,Neha,19,F,95.0,94,58.0,96,98,285.0,71.25,B,7
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F,10
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3

In [36]:
df[df["percentage"]>=80]

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3

In [37]:
df[df["Attendance"]<75]

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F,10

In [38]:
df[(df["percentage"]>=75) & (df["Attendance"]>=80)]

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3

In [39]:
df.nlargest(1,"percentage")

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1

In [40]:
df[df["percentage"]==df["percentage"].min()]

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.0,F,10

In [41]:
df.sort_values("percentage",ascending=False)

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6
7,Neha,19,F,95.0,94,58.0,96,98,285.0,71.25,B,7
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F,10

In [42]:
df["Rank"]=df["percentage"].rank(ascending=False).astype(int)
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6
7,Neha,19,F,95.0,94,58.0,96,98,285.0,71.25,B,7
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F,10
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3

In [43]:
df.groupby("Gender")["total_marks"].mean()

Gender
F    331.8
M    257.0
Name: total_marks, dtype: float64

In [44]:
df.groupby("Gender")["Attendance"].mean()

Gender
F    93.2
M    76.4
Name: Attendance, dtype: float64

In [45]:

df.groupby("Gender")[["Python","Maths","DBMS","English"]].agg("mean")

        Python  Maths  DBMS  English
Gender
F        86.80   87.4  80.6     88.6
M        66.75   67.6  68.6     67.4

In [46]:
# df.isna().sum()
df.isna().sum().sum()

np.int64(1)

In [47]:
df[df["Python"]==df["Python"].fillna(df["Python"].mean())]

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6
7,Neha,19,F,95.0,94,58.0,96,98,285.0,71.25,B,7
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3

In [55]:
df["DBMS"]=df["DBMS"].bfill()
df

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4
1,Riya,19,F,92.0,88,95.0,90,96,365.0,91.25,A+,1
2,Rahul,21,M,65.0,72,68.0,70,75,275.0,68.75,C,8
3,Sneha,20,F,78.0,85,80.0,82,88,325.0,81.25,A,4
4,Karan,19,M,45.0,58,52.0,60,65,215.0,53.75,D,9
5,Priya,20,F,88.0,91,86.0,89,94,354.0,88.50,A,2
6,Arjun,21,M,72.0,68,75.0,71,80,286.0,71.50,B,6
7,Neha,19,F,95.0,94,58.0,96,98,285.0,71.25,B,7
8,Vikas,20,M,NaN,62,58.0,64,70,184.0,46.00,F,10
9,Anjali,21,F,81.0,79,84.0,86,90,330.0,82.50,A,3

In [56]:
mkv = df[df["Name"]=="Aman"]
print(f"----- Select the Student -------\n")
print(mkv.T.to_string(header=False))

----- Select the Student -------

Name          Aman
Age             20
Gender           M
Python        85.0
Maths           78
DBMS          90.0
English         72
Attendance      92
total_marks  325.0
percentage   81.25
grade            A
Rank             4

,Name,Age,Gender,Python,Maths,DBMS,English,Attendance,total_marks,percentage,grade,Rank
0,Aman,20,M,85.0,78,90.0,72,92,325.0,81.25,A,4